development: &DEFAULTS
  adapter: "postgresql"
  encoding: "unicode"
  database: "events_bulletin"
  username: "christram"
  pool: 5

test:
  <<: *DEFAULTS
  database: "events_bulletin_test"

integration:
  <<: *DEFAULTS
  database: "events_bulletin_integration"
